### ISSUE TITLE
Please add support for Keynote 12.1 (7034.0.86, 1A95)

### ISSUE THREAD

**Issue by SheetJSDev** [psobot/keynote-parser#39]
From a blank workbook with the default template, `Index/DocumentStylesheet.iwa` fails to parse with message

```
NotImplementedError: Don't know how to parse Protobuf message type 26
```

**Comment by gaitskell** [comment]
What can we do to help with additional information you would require in order to patch the code? I cannot workout what the specific protobuf message types mean - what is a type 26 or a type 6383?

**Comment by SheetJSDev** [comment]
There are some instructions in https://github.com/psobot/keynote-parser#updates .  They should theoretically work since @masaccio has a similar setup for https://github.com/masaccio/numbers-parser/ 

The referenced types are defined in https://github.com/psobot/keynote-parser/blob/master/keynote_parser/mapping.py#L70 .  Under the hood, the file has a series of records with a record type and corresponding data.  `keynote-parser` errors when it sees fields that are not known in advance.  It may not be a bad idea to add a mode that skips unrecognized fields.

**Comment by gaitskell** [comment]
Thank you - that is very helpful - I will see if I can re-make the protobuf code for keynote-parser as described in more detail in the numbers-parser readme. (I couldn't find the "dumper" directory mentioned in the readme for keynote-parser. It may be because I am working on Apple Silicon MacOS.) I am also trying to work inside a venv rather than using my system-wide homebrew so I need to change instructions some.
